typography_spectrum: 0.2088986444287002
color:
  brandStrength: 0.343223309610039
  lightness: 0.240913943387568
  saturation: 0.6253177293110639
  rhythmicContrast: 0.31860350514762104
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.020492006791755557
name: Collectorum
title: For collectors
description: ...from an hipercollector
